### ISSUE TITLE
Crash on bare config

### ISSUE THREAD

**Issue by h0tw1r3** [mickelson/attract#145]
Thought this was a bug on OSX at first, but does it on Linux also (did't check windows).

```
1. delete personal settings (rm -rf ~/.attract)
2. start attract
3. exit attract without setting anything up.
4. start attract
5. crash...
````

```
#0  0x00000000006cd403 in FeTextPrimative::setString (this=0x7fffffffbd00, 
    t="C\000\000\000o\000\000\000n\000\000\000f\000\000\000i\000\000\000g\000\000\000u\000\000\000r\000\000\000e\000\000\000 \000\000\000e\000\000\000m\000\000\000u\000\000\000l\000\000\000a\000\000\000t\000\000\000o\000\000\000r\000\000\000", position=1) at src/tp.cpp:231
#1  0x00000000006ccfef in FeTextPrimative::setString (this=0x7fffffffbd00, t="Configure emulator") at src/tp.cpp:163
#2  0x00000000006c560f in FeOverlay::display_config_dialog (this=0x7fffffffd550, m=0x7fffffffd258, parent_setting_changed=@0x7fffffffc7f7: false)
    at src/fe_overlay.cpp:687
#3  0x00000000006c58f1 in FeOverlay::display_config_dialog (this=0x7fffffffd550, m=0x7fffffffd250, parent_setting_changed=@0x7fffffffd24f: false)
    at src/fe_overlay.cpp:755
#4  0x00000000006c4e67 in FeOverlay::config_dialog (this=0x7fffffffd550) at src/fe_overlay.cpp:573
#5  0x000000000071bab9 in main (argc=1, argv=0x7fffffffe0d8) at src/main.cpp:378
```

**Comment by h0tw1r3** [comment]
Thanks for the quick fix.
