### ISSUE TITLE
Segmentation fault in v2.2.0-5-dirty (in nouveau_dri)

### ISSUE THREAD

**Issue by tblum** [mickelson/attract#276]
I get a segfault when running attract. Both from the PPA and when building it from source (git). 
```
Starting Attract-Mode v2.2.0-5 (Linux)
Config file not found: /home/troels/.attract/attract.cfg, performing initial setup.
 - Constructed 1 filters in 0 ms (1 comparisons)
Segmentation fault (core dumped)
```
Running on ubuntu:
```
$ lsb_release -a
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.1 LTS
Release:	16.04
Codename:	xenial
$ uname -a
Linux mufkarkade 4.4.0-51-generic #72-Ubuntu SMP Thu Nov 24 18:29:54 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```
The segfault is happening in nouveau_dri.so:
```
Thread 1 "attract" received signal SIGSEGV, Segmentation fault.
0x00007fffdec4fbf5 in ?? () from /usr/lib/x86_64-linux-gnu/dri/nouveau_dri.so
(gdb) bt
#0  0x00007fffdec4fbf5 in ?? () from /usr/lib/x86_64-linux-gnu/dri/nouveau_dri.so
#1  0x00007fffde9e8bcf in ?? () from /usr/lib/x86_64-linux-gnu/dri/nouveau_dri.so
#2  0x00007fffde9e58ad in ?? () from /usr/lib/x86_64-linux-gnu/dri/nouveau_dri.so
#3  0x00007fffde9eda61 in ?? () from /usr/lib/x86_64-linux-gnu/dri/nouveau_dri.so
#4  0x00007ffff7bbcbd1 in sf::RenderTarget::clear(sf::Color const&) ()
   from /usr/lib/x86_64-linux-gnu/libsfml-graphics.so.2.3
#5  0x000000000071f93b in FeOverlay::event_loop (this=0x7fffffffd740, ctx=...)
    at src/fe_overlay.cpp:1323
#6  0x000000000071be8c in FeOverlay::languages_dialog (this=0x7fffffffd740) at src/fe_overlay.cpp:505
#7  0x000000000076fb81 in main (argc=1, argv=0x7fffffffe5c8) at src/main.cpp:121

```
Let me know if I can help with any more info :)

Best regards
Troels

**Comment by mickelson** [comment]
sorry I've completely overlooked this issue. If you are still experiencing the problem please reopen.
