### ISSUE TITLE
Segmentation fault on build romlist for Neo-Geo AES

### ISSUE THREAD

**Issue by TiBeN** [mickelson/attract#346]
Hi, 

Using Ubuntu 16.10, Attract 2.2.1 (debug enabled) and Mame (0.179|0.183), a segmentation fault is thrown when trying to build romlist for Neo Geo AES. Here is the GDB stacktrace : 

```
Reading symbols from /home/ben/src/15khz-arcade-pkg/vendor/attract-2.2.1/attract...done.
(gdb) run -b mame-aes
Starting program: /home/ben/src/15khz-arcade-pkg/vendor/attract-2.2.1/attract -b mame-aes
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
*** Generating Collection/Rom List: mame-aes
 - Found 254 files.
100%

Program received signal SIGSEGV, Segmentation fault.
0x0000555555855240 in (anonymous namespace)::get_crc (full_path="/srv/pkg/roms/mame/neogeo/mslug5.zip", exts=std::vector of length 2, capacity 2 = {...}) at src/scraper_xml.cpp:146
146             myfile.read( buff, size );
(gdb) backtrace
#0  0x0000555555855240 in (anonymous namespace)::get_crc (full_path="/srv/pkg/roms/mame/neogeo/mslug5.zip", exts=std::vector of length 2, capacity 2 = {...}) at src/scraper_xml.cpp:146
#1  0x0000555555859041 in FeListSoftwareParser::parse (this=0x7fffffffbf10, prog="/usr/local/bin/mame64", work_dir="", system_names=std::vector of length 2, capacity 2 = {...}) at src/scraper_xml.cpp:933
#2  0x00005555558615c7 in FeSettings::apply_xml_import (this=0x7fffffffc9b0, c=..., include_gdb=true) at src/scraper_general.cpp:391
#3  0x00005555558621be in FeSettings::build_romlist (this=0x7fffffffc9b0, task_list=std::vector of length 1, capacity 1 = {...}, output_name="", filter=..., full=false) at src/scraper_general.cpp:525
#4  0x000055555580402b in process_args (argc=3, argv=0x7fffffffdf18, config_path="", cmdln_font="", process_console=@0x7fffffffcf58: false) at src/fe_cmdline.cpp:309
#5  0x00005555558ec47e in main (argc=3, argv=0x7fffffffdf18) at src/main.cpp:51
(gdb) 
```

and the emulator configuration:

```
executable           /usr/local/bin/mame64
args                 -waitvsync [system] [name]
rompath              /srv/pkg/roms/mame/neogeo
romext               .zip;.7z
system               aes;SNK Neo-Geo AES
info_source          listsoftware
exit_hotkey          S
artwork    flyer           $HOME/.attract/scraper/mame-neogeo/flyer
artwork    marquee         $HOME/.attract/scraper/mame-neogeo/marquee
artwork    snap            $HOME/.attract/scraper/mame-neogeo/snap
artwork    wheel           $HOME/.attract/scraper/mame-neogeo/wheel
```

**Comment by waltertt** [comment]
hi, TiBeN!
I've encountered the exactly same problem, any suggestion do you have? thanks in advance

**Comment by TiBeN** [comment]
Hi waltertt, 

Unfortunately not. I've stopped to use Attract Mode for now (i'm busy at other things) but still interested by this issue as i plan to reinstall my arcade setup soon.
